; Chinese text for the pages used by this installer. Other messages inherit Inno Setup defaults.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI
DialogFontSize=9
WelcomeFontName=Microsoft YaHei UI
WelcomeFontSize=14
[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
SetupLdrStartupMessage=即将安装 %1，是否继续？
SetupAlreadyRunning=安装程序已在运行。
SetupFileCorrupt=安装文件损坏，请重新下载程序。
WindowsVersionNotSupported=此程序不支持当前 Windows 版本。
SetupAppRunningError=%1 正在运行。%n%n请先关闭程序，再点击“确定”继续安装。
UninstallAppRunningError=%1 正在运行。%n%n请先关闭程序，再点击“确定”继续卸载。
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将不会完成安装。%n%n是否退出？
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)
ClickNext=点击“下一步”继续，或点击“取消”退出安装。
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=选择文件夹，然后点击“确定”。
NewFolderName=新建文件夹
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=本程序将安装 [name/ver]。%n%n软件离线运行，计划自动保存在本机。升级与卸载会保留个人计划数据。
WizardSelectDir=选择安装位置
SelectDirDesc=将 [name] 安装到哪里？
SelectDirLabel3=程序将安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续；更改位置请点击“浏览”。
DiskSpaceGBLabel=至少需要 [gb] GB 可用空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用空间。
DirExistsTitle=文件夹已存在
DirExists=文件夹：%n%n%1%n%n已存在，是否继续安装到这里？
WizardSelectTasks=选择附加任务
SelectTasksDesc=需要创建哪些快捷方式？
SelectTasksLabel2=选择需要执行的附加任务，然后点击“下一步”。
WizardReady=准备安装
ReadyLabel1=即将在电脑上安装 [name]。
ReadyLabel2a=点击“安装”开始；修改设置请点击“上一步”。
ReadyLabel2b=点击“安装”开始安装。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单文件夹：
ReadyMemoTasks=附加任务：
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已安装完成。
FinishedLabel=[name] 已安装完成，可通过快捷方式打开软件。
ClickFinish=点击“完成”退出安装向导。
RunEntryExec=打开 %1
StatusCreateDirs=正在创建文件夹...
StatusExtractFiles=正在解压文件...
StatusCreateIcons=正在创建快捷方式...
StatusCreateRegistryEntries=正在保存安装信息...
StatusSavingUninstall=正在保存卸载信息...
StatusRunProgram=正在完成安装...
StatusClosingApplications=正在关闭运行中的程序...
StatusRollback=正在恢复安装前状态...
ConfirmUninstall=是否卸载 %1？个人计划数据会保留。
UninstallStatusLabel=正在卸载 %1，请稍候。
UninstalledAll=%1 已卸载。个人计划数据仍保留在本机。
StatusUninstalling=正在卸载 %1...
